export type Update = {
  id: string; date: string; product: string; title: string; summary: string;
  newText: string; useText: string; audience: string; status: string; source: string;
};

export const updates: Update[] = [
  {id:'word-documentproces',date:'2026-10-03',product:'Microsoft 365 Copilot',title:'Copilot in Word helpt nu bij het volledige documentproces',summary:'Van schrijven naar reviewen, opmaak en hergebruik van visuele elementen.',newText:'Copilot in Word ontwikkelt zich verder van schrijfhulp naar ondersteuning tijdens het hele documentproces. Referentiedocumenten kunnen tekst en visuele elementen leveren voor nieuwe content.',useText:'Gebruik een bestaand, goedgekeurd document als referentie voor een nieuw voorstel, rapport of projectdocument. Zo ontstaat sneller een consistente eerste versie.',audience:'Kenniswerkers, communicatie, HR, sales en consultants.',status:'In uitrol',source:'Microsoft 365 Roadmap'},
  {id:'powerpoint-brand-kits',date:'2026-10-03',product:'PowerPoint',title:'Brand Kits geven Copilot meer grip op jouw huisstijl',summary:'Logo’s, kleuren en lettertypes als merkkader bij nieuwe presentaties.',newText:'Copilot kan merkafspraken beter meenemen bij het maken van presentaties. Daarmee wordt de stap van inhoud naar een herkenbare bedrijfspresentatie kleiner.',useText:'Laat medewerkers een eerste presentatie opbouwen vanuit een vaste merkset en controleer daarna alleen nog inhoud, nuance en uitzonderingen.',audience:'Marketing, communicatie, sales en consultants.',status:'Preview',source:'Microsoft 365 Roadmap'},
  {id:'copilot-studio-agents',date:'2026-10-03',product:'Copilot Studio',title:'Agents nemen meer terugkerende werkzaamheden over',summary:'Copilot Studio groeit van chatbot naar praktische digitale collega.',newText:'Agents kunnen processen volgen, informatie verzamelen en acties voorbereiden. Daardoor verschuift Copilot steeds meer van antwoorden geven naar werk ondersteunen.',useText:'Start met één afgebakend proces, bijvoorbeeld het voorbereiden van een klantoverleg of het verzamelen van projectstatussen.',audience:'Teams met repeterende kennisprocessen en proceseigenaren.',status:'Aangekondigd',source:'Microsoft Copilot Studio'},
  {id:'teams-meeting-recap',date:'2026-10-02',product:'Microsoft Teams',title:'Copilot maakt vergaderrecaps bruikbaarder voor vervolgacties',summary:'Samenvattingen leggen meer nadruk op besluiten, taken en open punten.',newText:'De recap-ervaring wordt verder verfijnd zodat gebruikers sneller van een vergadering naar concrete opvolging kunnen.',useText:'Gebruik de recap als startpunt voor taken, projectupdates en een korte follow-up naar deelnemers.',audience:'Projectteams, managers en consultants.',status:'In uitrol',source:'Microsoft 365 Roadmap'}
];
