'use client';
import { useMemo,useState } from 'react';
import { updates,type Update } from './data';
type View='today'|'archive'|'search'|'about';
const products=['Alle','Copilot','Teams','Outlook','Word','Excel','PowerPoint','SharePoint','Agents','Copilot Studio','Beveiliging'];
function Logo(){return <div className="advLogo"><span>ad</span><i>v</i><span>antive</span></div>}
function Icon({product}:{product:string}){const p=product.toLowerCase();const label=p.includes('teams')?'T':p.includes('outlook')?'O':p.includes('word')?'W':p.includes('excel')?'X':p.includes('powerpoint')?'P':p.includes('studio')?'AI':'C';return <div className={'productIcon '+label.toLowerCase()}>{label}</div>}
function Status({value}:{value:string}){return <span className={'status '+value.toLowerCase().replaceAll(' ','-')}>{value.toUpperCase()}</span>}
function Card({item,onOpen}:{item:Update;onOpen:()=>void}){return <button className="newsCard" onClick={onOpen}><Icon product={item.product}/><div className="newsCopy"><div className="metaTop"><Status value={item.status}/><span>{item.product}</span></div><h3>{item.title}</h3><p>{item.summary}</p></div><time>{new Date(item.date+'T12:00:00').toLocaleDateString('nl-NL',{day:'numeric',month:'short',year:'numeric'})}</time><b className="arrow">›</b></button>}
function Detail({item,onClose}:{item:Update;onClose:()=>void}){return <div className="detail"><div className="detailVisual"><Icon product={item.product}/><button onClick={onClose}>×</button></div><div className="detailBody"><div className="metaTop"><Status value={item.status}/><span>{item.product}</span></div><h2>{item.title}</h2><time>{new Date(item.date+'T12:00:00').toLocaleDateString('nl-NL',{day:'numeric',month:'long',year:'numeric'})}</time><section><b>▣</b><div><h4>Wat is er nieuw?</h4><p>{item.newText}</p></div></section><section><b>♢</b><div><h4>Wat kun je ermee?</h4><p>{item.useText}</p></div></section><section><b>♧</b><div><h4>Voor wie is dit relevant?</h4><p>{item.audience}</p></div></section><section><b>↗</b><div><h4>Bron</h4><p>{item.source}</p></div></section></div></div>}
export default function Home(){const [view,setView]=useState<View>('today');const [query,setQuery]=useState('');const [filter,setFilter]=useState('Alle');const [selected,setSelected]=useState<Update|null>(null);const today='2026-10-03';const filtered=useMemo(()=>updates.filter(u=>{const q=query.toLowerCase();const search=!q||[u.title,u.summary,u.product,u.newText,u.useText].join(' ').toLowerCase().includes(q);const f=filter==='Alle'||u.product.toLowerCase().includes(filter.toLowerCase())||(filter==='Copilot'&&u.product.includes('365'));return search&&f}),[query,filter]);const visible=view==='today'?filtered.filter(u=>u.date===today):filtered;return <main><header><div className="topbar"><Logo/><nav><button className={view==='today'?'active':''} onClick={()=>setView('today')}>⌂ <span>Vandaag</span></button><button className={view==='archive'?'active':''} onClick={()=>setView('archive')}>▣ <span>Archief</span></button><button className={view==='search'?'active':''} onClick={()=>setView('search')}>⌕ <span>Zoeken</span></button><button className={view==='about'?'active':''} onClick={()=>setView('about')}>ⓘ <span>Over</span></button></nav><small>Daily Microsoft Copilot<br/>door Chris Munten</small><b className="hamb">☰</b></div></header>{view==='today'&&<><section className="hero"><div className="heroText"><i></i><h1>Daily Microsoft Copilot</h1><h2>De dagelijkse update over Microsoft Copilot</h2><p>door Chris Munten · Programma-manager AI Advantive</p><div className="date">▣ &nbsp; Vandaag — 3 oktober 2026</div></div><div className="heroArt"><div className="copilotMark">∞</div><span className="app a">T</span><span className="app b">W</span><span className="app c">O</span><span className="app d">P</span><span className="app e">X</span></div></section><div className="filters">{products.map(p=><button key={p} className={filter===p?'active':''} onClick={()=>setFilter(p)}>{p}</button>)}</div></>}
<section className={'content '+(view!=='today'?'subpage':'')}>{selected?<Detail item={selected} onClose={()=>setSelected(null)}/>:view==='about'?<div className="panel"><i></i><h1>Over deze app</h1><p>Daily Microsoft Copilot is een initiatief van Chris Munten, Programma-manager AI bij Advantive. Deze app biedt je dagelijks een overzicht van de belangrijkste ontwikkelingen rondom Microsoft Copilot, in begrijpelijke taal en met praktische toepassingen.</p><div className="feature"><b>◷</b><div><strong>Altijd actueel</strong><p>Iedere dag automatisch vernieuwd om 05:00 uur.</p></div></div><div className="feature"><b>✓</b><div><strong>Betrouwbare bronnen</strong><p>Gebaseerd op officiële Microsoft-aankondigingen en relevante nieuwsbronnen.</p></div></div></div>:<><div className="pageTitle">{view==='archive'&&<><i></i><h1>Archief</h1><p>Blader door alle eerdere Copilot-updates.</p></>}{view==='search'&&<><i></i><h1>Zoeken</h1><p>Zoek in alle artikelen, titels en inhoud.</p></>}</div>{view!=='today'&&<div className="searchBox">⌕ <input autoFocus={view==='search'} value={query} onChange={e=>setQuery(e.target.value)} placeholder={view==='archive'?'Zoek in archief...':'Zoeken...'}/>{query&&<button onClick={()=>setQuery('')}>×</button>}</div>}<div className="cards">{visible.map(u=><Card key={u.id} item={u} onOpen={()=>setSelected(u)}/>)}</div>{visible.length===0&&<div className="empty">Geen updates gevonden.</div>}</>}</section><div className="mobileNav"><button className={view==='today'?'active':''} onClick={()=>{setView('today');setSelected(null)}}>⌂<span>Vandaag</span></button><button className={view==='archive'?'active':''} onClick={()=>{setView('archive');setSelected(null)}}>▣<span>Archief</span></button><button className={view==='search'?'active':''} onClick={()=>{setView('search');setSelected(null)}}>⌕<span>Zoeken</span></button><button className={view==='about'?'active':''} onClick={()=>{setView('about');setSelected(null)}}>ⓘ<span>Over</span></button></div></main>}
