'use client';
import { useEffect,useMemo,useState } from 'react';
import { updates as fallbackUpdates,type Update } from './data';
type View='today'|'all'|'archive'|'search'|'about'; type WebResult={title:string;url:string;description:string;date:string|null;source:string}; type LiveItem={title:string;url:string;description:string;date:string|null;source:string;product:string;status:string};
const products=['Alle','Copilot','Teams','Outlook','Word','Excel','PowerPoint','Meer'];
const navItems:[View,string,string][]= [['today','Vandaag','⌂'],['all','Updates','▤'],['archive','Archief','◷'],['search','Zoeken','⌕'],['about','Over','ⓘ']];
function Logo(){return <a className="brand" href="https://www.advantive.nl/" target="_blank" rel="noopener noreferrer"><img className="advLogoImg" src="/Advantive%20logo.png" alt="Advantive"/><span><b>Daily Copilot</b><small>Microsoft 365 nieuws & duiding</small></span></a>}
const glyph=(p:string)=>p==='Alle'?'▦':p==='Copilot'?'✦':p==='Teams'?'T':p==='Outlook'?'O':p==='Word'?'W':p==='Excel'?'X':p==='PowerPoint'?'P':'•••';
function Icon({product}:{product:string}){const p=product.toLowerCase();const label=p.includes('teams')?'T':p.includes('outlook')?'O':p.includes('word')?'W':p.includes('excel')?'X':p.includes('powerpoint')?'P':'✦';return <div className={'productIcon '+label.toLowerCase()}>{label}</div>}
function Status({value}:{value:string}){return <span className={'status '+value.toLowerCase().replaceAll(' ','-')}>{value.toUpperCase()}</span>}
const isUrl=(s:string)=>/^https?:\/\//i.test(s);
function Card({item,onOpen}:{item:Update;onOpen:()=>void}){return <article className="newsCard" role="button" tabIndex={0} onClick={onOpen} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onOpen()}}><Icon product={item.product}/><div className="newsCopy"><div className="metaTop"><Status value={item.status}/><span>{item.product}</span><span className="dot">•</span><time>{new Date(item.date+'T12:00:00').toLocaleDateString('nl-NL',{day:'numeric',month:'short'})}</time></div><h3>{item.title}</h3><p>{item.summary}</p>{isUrl(item.source)&&<a className="cardSource" href={item.source} target="_blank" rel="noopener noreferrer" onClick={e=>e.stopPropagation()}>Originele bron ↗</a>}</div><b className="arrow">›</b></article>}
function Detail({item,onClose}:{item:Update;onClose:()=>void}){return <div className="detail"><div className="detailVisual"><Icon product={item.product}/><button aria-label="Sluiten" onClick={onClose}>×</button></div><div className="detailBody"><div className="metaTop"><Status value={item.status}/><span>{item.product}</span></div><h2>{item.title}</h2><time>{new Date(item.date+'T12:00:00').toLocaleDateString('nl-NL',{day:'numeric',month:'long',year:'numeric'})}</time><section><b>▣</b><div><h4>Samenvatting</h4><p>{item.newText}</p></div></section><section><b>♢</b><div><h4>Wat kun je ermee?</h4><p>{item.useText}</p></div></section><section><b>♧</b><div><h4>Voor wie is dit relevant?</h4><p>{item.audience}</p></div></section><section><b>↗</b><div><h4>Originele bron</h4>{isUrl(item.source)?<a className="sourceLink" href={item.source} target="_blank" rel="noopener noreferrer">Open het originele artikel ↗</a>:<p>{item.source}</p>}</div></section></div></div>}
export default function Home(){const [view,setView]=useState<View>('today'),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('Alle');const [selected,setSelected]=useState<Update|null>(null),[web,setWeb]=useState<WebResult[]>([]),[live,setLive]=useState<Update[]>([]),[loadingNews,setLoadingNews]=useState(true),[loading,setLoading]=useState(false),[sort,setSort]=useState<'recent'|'relevance'>('recent');const dateInfo=useMemo(()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Amsterdam',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=(t:string)=>parts.find(p=>p.type===t)?.value||'';const today=`${get('year')}-${get('month')}-${get('day')}`;return {today,label:new Date(today+'T12:00:00').toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long'})}},[]);
useEffect(()=>{let active=true;fetch('/api/news',{cache:'no-store'}).then(r=>r.json()).then(j=>{if(!active)return;const rows=(j.items||[]).map((x:LiveItem,i:number)=>{const date=x.date?new Date(x.date).toISOString().slice(0,10):dateInfo.today;return{id:`live-${date}-${i}-${x.title.slice(0,20)}`,date,product:x.product||'Microsoft 365 Copilot',title:x.title,summary:x.description||'Nieuwe Microsoft Copilot-update.',newText:x.description||'Nieuwe ontwikkeling rond Microsoft Copilot.',useText:'Bekijk de oorspronkelijke bron voor details, beschikbaarheid, licentie-impact en praktische toepassing binnen jouw Microsoft 365-omgeving.',audience:'Microsoft 365-gebruikers, beheerders, consultants en AI-professionals.',status:x.status||'Copilot update',source:x.url||x.source||'Microsoft'} as Update});setLive(rows)}).catch(()=>setLive([])).finally(()=>active&&setLoadingNews(false));return()=>{active=false}},[dateInfo.today]);
const allUpdates=live.length?live:fallbackUpdates;const filtered=useMemo(()=>allUpdates.filter(u=>{const q=query.toLowerCase(),hay=[u.title,u.summary,u.product,u.newText,u.useText].join(' ').toLowerCase();return(!q||hay.includes(q))&&(filter==='Alle'||filter==='Meer'||hay.includes(filter.toLowerCase())||(filter==='Copilot'&&hay.includes('copilot')))}),[query,filter,allUpdates]);const visible=useMemo(()=>{const sorted=[...filtered].sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id));if(view==='today'){const today=sorted.filter(u=>u.date===dateInfo.today);if(today.length>=5)return today;return [...today,...sorted.filter(u=>u.date!==dateInfo.today).slice(0,5-today.length)]}if(view==='archive')return sorted.filter(u=>u.date<dateInfo.today);return sorted},[view,filtered,dateInfo.today]);const webSorted=useMemo(()=>sort==='recent'?[...web].sort((a,b)=>(b.date||'').localeCompare(a.date||'')):web,[web,sort]);async function searchInternet(){if(query.trim().length<2)return;setLoading(true);setWeb([]);try{const r=await fetch('/api/search?q='+encodeURIComponent(query));const j=await r.json();setWeb(j.results||[])}finally{setLoading(false)}}const go=(v:View)=>{setView(v);setMenu(false);setFilter('Alle');setSelected(null);if(v==='today'||v==='all')setQuery('');window.scrollTo({top:0,behavior:'smooth'})};const showAll=()=>go('all');
return <main><header><div className="topbar"><Logo/><nav aria-label="Hoofdnavigatie">{navItems.map(([v,label])=><button key={v} className={view===v?'active':''} onClick={()=>go(v)}>{label}</button>)}</nav><div className="headerActions"><button className="quickSearch" onClick={()=>go('search')} aria-label="Zoeken">⌕</button><button className="hamb" aria-label="Menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>☰</button>{menu&&<div className="headerMenu">{navItems.map(([v,label,icon])=><button key={v} className={view===v?'active':''} onClick={()=>go(v)}><b>{icon}</b><span>{label}</span></button>)}</div>}</div></div></header>
{view==='today'&&<><section className="hero heroBanner"><img src="/header%20linkedin.png" alt="Advantive Programma Manager AI Microsoft Copilot"/></section><section className="dashboardBar"><div><small>VANDAAG</small><strong>{dateInfo.label}</strong></div><div className="fresh"><i/> Dagelijks bijgewerkt om 05:00</div></section><div className="filters">{products.map(p=><button key={p} className={filter===p?'active':''} onClick={()=>setFilter(p)}><b className={'filterGlyph g'+p}>{glyph(p)}</b>{p}</button>)}</div><div className="sectionHead"><div><span>MICROSOFT COPILOT</span><h2>Laatste updates</h2></div><button onClick={showAll}>Alle updates <b>→</b></button></div></>}
{view==='search'&&<div className="filters searchFilters">{products.map(p=><button key={p} className={filter===p?'active':''} onClick={()=>setFilter(p)}>{p}</button>)}</div>}
<section className={'content '+(view!=='today'?'subpage':'')}>{selected?<Detail item={selected} onClose={()=>setSelected(null)}/>:view==='about'?<div className="panel"><span className="kicker">DAILY COPILOT</span><h1>Over deze app</h1><p className="lead">Dagelijks de belangrijkste ontwikkelingen rondom Microsoft Copilot, begrijpelijk en praktisch samengevat.</p><div className="feature"><b>◷</b><div><strong>Altijd actueel</strong><p>Iedere ochtend om 05:00 uur vernieuwd.</p></div></div><div className="feature"><b>✓</b><div><strong>Betrouwbare bronnen</strong><p>Nieuws, aankondigingen, functies en licentiewijzigingen uit betrouwbare Microsoft-bronnen.</p></div></div><div className="feature"><b>↗</b><div><strong>Altijd naar het origineel</strong><p>Elke Nederlandse samenvatting bevat een directe link naar de oorspronkelijke publicatie.</p></div></div></div>:<><div className="pageTitle">{view==='all'&&<><span className="kicker">ACTUEEL</span><h1>Alle Copilot-updates</h1><p>Nieuws en ontwikkelingen, nieuwste eerst.</p></>}{view==='archive'&&<><span className="kicker">HISTORIE</span><h1>Archief</h1><p>Alle eerdere Copilot-updates op één plek.</p></>}{view==='search'&&<><span className="kicker">ONTDEKKEN</span><h1>Zoeken</h1><p>Doorzoek Daily Copilot en betrouwbare Microsoft-bronnen.</p></>}</div>{(view==='archive'||view==='search'||view==='all')&&<div className="searchBox"><span>⌕</span><input autoFocus={view==='search'} value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&view==='search'&&searchInternet()} placeholder={view==='archive'?'Zoek in archief...':view==='all'?'Zoek in alle updates...':'Waar wil je meer over weten?'}/>{query&&<button onClick={()=>{setQuery('');setWeb([])}}>×</button>}{view==='search'&&<button className="webSearch" onClick={searchInternet}>Zoek internet</button>}</div>}{view==='search'&&<div className="searchTools"><span>{web.length?web.length+' internetresultaten':''}</span><label>Sorteren <select value={sort} onChange={e=>setSort(e.target.value as 'recent'|'relevance')}><option value="recent">Meest recent</option><option value="relevance">Relevantie</option></select></label></div>}{view!=='search'&&<div className="cards">{loadingNews&&<div className="empty">Actuele Microsoft Copilot-updates worden geladen…</div>}{!loadingNews&&visible.map(u=><Card key={u.id} item={u} onOpen={()=>setSelected(u)}/>)}{!loadingNews&&visible.length===0&&<div className="empty">Er zijn op dit moment geen updates gevonden.</div>}</div>}{view==='search'&&<div className="webResults">{loading&&<div className="empty">Betrouwbare bronnen worden doorzocht…</div>}{webSorted.map((r,i)=><a className="webResult" href={r.url} target="_blank" rel="noreferrer" key={r.url+i}><div><small>{r.source}</small><h4>{r.title}</h4><p>{r.description}</p></div><b>↗</b></a>)}</div>}</>}</section>
<nav className="mobileNav" aria-label="Mobiele navigatie">{navItems.slice(0,4).map(([v,label,icon])=><button key={v} className={view===v?'active':''} onClick={()=>go(v)}><b>{icon}</b><span>{label}</span></button>)}</nav></main>}
