import { NextResponse } from 'next/server';

export const dynamic='force-dynamic';

type Item={title:string;url:string;description:string;date:string|null;source:string;product:string;status:string};
type LearnResult={title?:string;url?:string;description?:string;lastUpdatedDate?:string};

const queries=['Microsoft 365 Copilot','Copilot Studio','Copilot Teams','Copilot Outlook','Copilot Word','Copilot Excel','Copilot PowerPoint','Copilot SharePoint','Copilot OneDrive','Copilot agents','Work IQ'];
const clean=(s='')=>s.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const product=(s:string)=>{const x=s.toLowerCase();if(x.includes('powerpoint'))return'PowerPoint';if(x.includes('excel'))return'Excel';if(x.includes('word'))return'Word';if(x.includes('outlook'))return'Outlook';if(x.includes('teams'))return'Teams';if(x.includes('sharepoint'))return'SharePoint';if(x.includes('onedrive'))return'OneDrive';if(x.includes('studio'))return'Copilot Studio';if(x.includes('agent'))return'Agents';return'Microsoft 365 Copilot'};
const trustedHosts=new Set(['learn.microsoft.com','www.microsoft.com','blogs.microsoft.com']);

const seed:Item[]=[
 {title:'4 manieren om te leren bouwen met Microsoft Copilot Studio',url:'https://www.microsoft.com/en-us/copilot/blog/copilot-studio/4-ways-to-learn-how-to-build-with-microsoft-copilot-studio/',description:'Microsoft bundelt vier praktische leerpaden voor Copilot Studio: verkennen, hands-on bouwen, vaardigheden valideren en gericht doorgroeien.',date:'2026-10-01T12:00:00Z',source:'Microsoft Copilot Blog',product:'Copilot Studio',status:'Microsoft update'},
 {title:'Usage-based billing voor nieuwe Microsoft 365 Copilot Business-licenties',url:'https://learn.microsoft.com/en-us/partner-center/announcements/2026-october',description:'Microsoft kondigt wijzigingen aan voor usage-based billing bij nieuwe Microsoft 365 Copilot Business-abonnementen via CSP, inclusief Copilot Credits en bestedingslimieten.',date:'2026-10-01T12:00:00Z',source:'Microsoft Learn / Partner Center',product:'Microsoft 365 Copilot',status:'Microsoft update'},
 {title:'Growth margin voor Microsoft 365 Copilot is live voor CSP-partners',url:'https://learn.microsoft.com/en-us/partner-center/announcements/2026-october',description:'Vanaf 1 oktober kunnen in aanmerking komende CSP-partners extra marge verdienen bij groei van strategische workloads, waaronder Microsoft 365 Copilot.',date:'2026-10-01T11:00:00Z',source:'Microsoft Learn / Partner Center',product:'Microsoft 365 Copilot',status:'Microsoft update'}
];

async function learn(q:string){const u=`https://learn.microsoft.com/api/search?search=${encodeURIComponent(q)}&locale=en-us&$top=20`;const r=await fetch(u,{headers:{Accept:'application/json','User-Agent':'Daily-Microsoft-Copilot/3.0'},cache:'no-store'});if(!r.ok)return[];const j=await r.json();return (Array.isArray(j.results)?j.results:[]).map((x:LearnResult)=>{let url=x.url||'';if(!url.startsWith('http'))url='https://learn.microsoft.com'+(url.startsWith('/')?'':'/')+url;let date:string|null=null;if(x.lastUpdatedDate){const d=new Date(x.lastUpdatedDate);if(!Number.isNaN(d.getTime()))date=d.toISOString()}return{title:clean(x.title),url,description:clean(x.description),date,source:'Microsoft Learn',product:product(`${x.title} ${x.description}`),status:'Microsoft update'} as Item})}

export async function GET(){try{const groups=await Promise.all(queries.map(learn));const now=new Date();const oldest=new Date(now);oldest.setUTCDate(oldest.getUTCDate()-5);oldest.setUTCHours(0,0,0,0);const seen=new Set<string>();const items=[...seed,...groups.flat()].filter(x=>{if(!x.title||!x.url||!x.date)return false;let host='';try{host=new URL(x.url).hostname}catch{return false}if(!trustedHosts.has(host))return false;const d=new Date(x.date);if(Number.isNaN(d.getTime())||d<oldest||d>now)return false;const key=(x.url.split('?')[0]+'|'+x.title).toLowerCase();if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,150);return NextResponse.json({items,updatedAt:new Date().toISOString(),windowDays:5,sources:['Microsoft Learn','Microsoft Copilot Blog','Microsoft Partner Center'],count:items.length},{headers:{'Cache-Control':'public, s-maxage=900, stale-while-revalidate=3600'}})}catch(e){console.error(e);return NextResponse.json({items:seed,error:'Live nieuws kon niet volledig worden opgehaald'},{status:200})}}
