import { NextResponse } from 'next/server';
import { databaseEnabled,readArchive,saveNews,type StoredNews } from '../../lib/news-db';

export const dynamic='force-dynamic';
type Item=StoredNews;
type LearnResult={title?:string;url?:string;description?:string;lastUpdatedDate?:string};
type Translation={index:number;title:string;description:string};
const queries=['Microsoft 365 Copilot','Microsoft Copilot whats new','Microsoft Copilot release notes','Microsoft Copilot roadmap','Microsoft Copilot licensing pricing Copilot Credits billing','Microsoft 365 Copilot Business CSP licensing','Copilot Studio release notes agents','Copilot Teams','Copilot Outlook','Copilot Word','Copilot Excel','Copilot PowerPoint','Copilot SharePoint','Copilot OneDrive','Copilot Chat','Copilot agents','Copilot Cowork','Work IQ','Microsoft Copilot admin governance security'];
const clean=(s='')=>s.replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const product=(s:string)=>{const x=s.toLowerCase();if(x.includes('powerpoint'))return'PowerPoint';if(x.includes('excel'))return'Excel';if(x.includes('word'))return'Word';if(x.includes('outlook'))return'Outlook';if(x.includes('teams'))return'Teams';if(x.includes('sharepoint'))return'SharePoint';if(x.includes('onedrive'))return'OneDrive';if(x.includes('studio'))return'Copilot Studio';if(x.includes('agent'))return'Agents';return'Microsoft 365 Copilot'};
const trustedHosts=new Set(['learn.microsoft.com','www.microsoft.com','microsoft.com','blogs.microsoft.com','techcommunity.microsoft.com']);
const relevant=(s:string)=>{const x=s.toLowerCase();return x.includes('copilot')||x.includes('work iq')||x.includes('agent builder')||x.includes('copilot credit')};
function statusFor(s:string){if(/licen|billing|pricing|credit|subscription|csp/i.test(s))return'Licentie-update';if(/release note/i.test(s))return'Release notes';if(/introduc|announc|launch/i.test(s))return'Aankondiging';return'Microsoft update'}
const seed:Item[]=[
 {title:'4 manieren om te leren bouwen met Microsoft Copilot Studio',url:'https://www.microsoft.com/en-us/copilot/blog/copilot-studio/4-ways-to-learn-how-to-build-with-microsoft-copilot-studio/',description:'Microsoft bundelt vier praktische leerpaden voor Copilot Studio: verkennen, hands-on bouwen, vaardigheden valideren en gericht doorgroeien.',date:'2026-10-01T12:00:00Z',source:'Microsoft Copilot Blog',product:'Copilot Studio',status:'Microsoft update'},
 {title:'Usage-based billing voor nieuwe Microsoft 365 Copilot Business-licenties',url:'https://learn.microsoft.com/en-us/partner-center/announcements/2026-october',description:'Microsoft wijzigt usage-based billing voor nieuwe Microsoft 365 Copilot Business-abonnementen via CSP, inclusief Copilot Credits, bestedingslimieten en beschikbaarheid.',date:'2026-10-01T12:00:00Z',source:'Microsoft Learn / Partner Center',product:'Microsoft 365 Copilot',status:'Licentie-update'},
 {title:'Wat is nieuw in Microsoft Copilot – september 2026',url:'https://techcommunity.microsoft.com/blog/microsoft-copilot-blog/what%E2%80%99s-new-in-microsoft-copilot--september-2026/4559107',description:'Microsoft bundelt nieuwe Copilot-mogelijkheden voor Teams, Outlook, Word, PowerPoint, SharePoint, OneDrive, agents, connectors en beheer.',date:'2026-09-30T12:00:00Z',source:'Microsoft Community Hub',product:'Microsoft 365 Copilot',status:'Microsoft update'}
];
async function learn(q:string){try{const u=`https://learn.microsoft.com/api/search?search=${encodeURIComponent(q)}&locale=en-us&$top=35`;const r=await fetch(u,{headers:{Accept:'application/json','User-Agent':'Daily-Microsoft-Copilot/7.0'},cache:'no-store'});if(!r.ok)return[];const j=await r.json();return (Array.isArray(j.results)?j.results:[]).map((x:LearnResult)=>{let url=x.url||'';if(!url.startsWith('http'))url='https://learn.microsoft.com'+(url.startsWith('/')?'':'/')+url;let date:string|null=null;if(x.lastUpdatedDate){const d=new Date(x.lastUpdatedDate);if(!Number.isNaN(d.getTime()))date=d.toISOString()}const title=clean(x.title),description=clean(x.description),p=product(`${title} ${description}`),status=statusFor(`${title} ${description}`);return{title,url,description,date,source:'Microsoft Learn',product:p,status} as Item})}catch{return[]}}
function extractOutputText(j:any){if(typeof j?.output_text==='string')return j.output_text;for(const o of j?.output||[])for(const c of o?.content||[])if(typeof c?.text==='string')return c.text;return''}
async function translateBatch(items:Item[]):Promise<Item[]>{const key=process.env.OPENAI_API_KEY;if(!key||!items.length)return items;const model=process.env.OPENAI_TRANSLATION_MODEL||'gpt-5-mini';const payload=items.map((x,index)=>({index,title:x.title,description:x.description,product:x.product,status:x.status}));try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model,instructions:'Je bent de Nederlandse eindredacteur van Advantive Daily Copilot News. Vertaal alle aangeleverde Microsoft Copilot-nieuwstitels en beschrijvingen volledig naar natuurlijk, professioneel en begrijpelijk Nederlands voor zakelijke Microsoft 365-gebruikers. Behoud officiële productnamen zoals Microsoft 365 Copilot, Copilot Studio, Teams, Word, Excel, PowerPoint, Outlook, SharePoint, OneDrive, Agents, Work IQ en Copilot Credits. Vertaal de inhoud trouw: voeg geen feiten toe en laat geen relevante informatie weg. Vermijd half-Engelse zinnen. Geef uitsluitend geldige JSON terug als array met exact de velden index, title en description. Maak descriptions compact maar inhoudelijk volledig, maximaal circa 450 tekens.',input:JSON.stringify(payload),temperature:0.1})});if(!r.ok){console.error('Translation API',r.status,await r.text());return items}const j=await r.json();let text=extractOutputText(j).trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();const translated=JSON.parse(text) as Translation[];const map=new Map(translated.map(x=>[x.index,x]));return items.map((item,index)=>{const t=map.get(index);return t?{...item,title:clean(t.title)||item.title,description:clean(t.description)||item.description}:item})}catch(e){console.error('Translation failed',e);return items}}
async function translateAll(items:Item[]){const out:Item[]=[];for(let i=0;i<items.length;i+=12)out.push(...await translateBatch(items.slice(i,i+12)));return out}
export async function GET(){try{const groups=await Promise.all(queries.map(learn));const now=new Date(),oldest=new Date(now);oldest.setUTCDate(oldest.getUTCDate()-14);oldest.setUTCHours(0,0,0,0);const seen=new Set<string>();const raw=[...seed,...groups.flat()].filter(x=>{if(!x.title||!x.url||!x.date||!relevant(`${x.title} ${x.description}`))return false;let host='';try{host=new URL(x.url).hostname.toLowerCase()}catch{return false}if(!trustedHosts.has(host))return false;const d=new Date(x.date);if(Number.isNaN(d.getTime())||d<oldest||d>now)return false;const key=x.url.split('?')[0].replace(/\/$/,'').toLowerCase();if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,300);const fresh=await translateAll(raw);let items=fresh,persisted=0;if(databaseEnabled()){persisted=await saveNews(fresh);items=await readArchive(1000)}return NextResponse.json({items,updatedAt:new Date().toISOString(),windowDays:14,persistentArchive:databaseEnabled(),persisted,count:items.length,language:'nl-NL',translationService:process.env.OPENAI_API_KEY?'OpenAI':'fallback-no-key',translationModel:process.env.OPENAI_TRANSLATION_MODEL||'gpt-5-mini',originalSourceLinks:true,sources:['Microsoft Learn','Microsoft 365 Copilot release notes','AI at Work Roadmap','Microsoft Copilot Blog','Microsoft Community Hub','Official Microsoft Blog','Microsoft Partner Center']},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);let items=seed;try{if(databaseEnabled()){const archived=await readArchive(1000);if(archived.length)items=archived}}catch{}return NextResponse.json({items,persistentArchive:databaseEnabled(),error:'Live nieuws kon niet volledig worden opgehaald'},{status:200,headers:{'Cache-Control':'no-store'}})}}
