import { NextResponse } from 'next/server';
import { databaseEnabled,readArchive,saveNews,type StoredNews } from '../../lib/news-db';

export const dynamic='force-dynamic';
type Item=StoredNews;
type LearnResult={title?:string;url?:string;description?:string;lastUpdatedDate?:string};
const queries=['Microsoft 365 Copilot','Microsoft Copilot whats new','Microsoft Copilot release notes','Microsoft Copilot roadmap','Microsoft Copilot licensing pricing Copilot Credits billing','Microsoft 365 Copilot Business CSP licensing','Copilot Studio release notes agents','Copilot Teams','Copilot Outlook','Copilot Word','Copilot Excel','Copilot PowerPoint','Copilot SharePoint','Copilot OneDrive','Copilot Chat','Copilot agents','Copilot Cowork','Work IQ','Microsoft Copilot admin governance security'];
const clean=(s='')=>s.replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const product=(s:string)=>{const x=s.toLowerCase();if(x.includes('powerpoint'))return'PowerPoint';if(x.includes('excel'))return'Excel';if(x.includes('word'))return'Word';if(x.includes('outlook'))return'Outlook';if(x.includes('teams'))return'Teams';if(x.includes('sharepoint'))return'SharePoint';if(x.includes('onedrive'))return'OneDrive';if(x.includes('studio'))return'Copilot Studio';if(x.includes('agent'))return'Agents';return'Microsoft 365 Copilot'};
const trustedHosts=new Set(['learn.microsoft.com','www.microsoft.com','microsoft.com','blogs.microsoft.com','techcommunity.microsoft.com']);
const relevant=(s:string)=>{const x=s.toLowerCase();return x.includes('copilot')||x.includes('work iq')||x.includes('agent builder')||x.includes('copilot credit')};
const dictionary:[RegExp,string][]=[[/what'?s new/gi,'Wat is er nieuw'],[/release notes?/gi,'release notes'],[/release plan/gi,'releaseplanning'],[/roadmap/gi,'roadmap'],[/licensing/gi,'licenties'],[/license/gi,'licentie'],[/pricing/gi,'prijzen'],[/billing/gi,'facturatie'],[/usage-based/gi,'op gebruik gebaseerde'],[/generally available|general availability/gi,'algemeen beschikbaar'],[/public preview/gi,'openbare preview'],[/private preview/gi,'besloten preview'],[/new features?/gi,'nieuwe functies'],[/new capabilities/gi,'nieuwe mogelijkheden'],[/improvements?/gi,'verbeteringen'],[/manage/gi,'beheren'],[/management/gi,'beheer'],[/security/gi,'beveiliging'],[/governance/gi,'governance'],[/users?/gi,'gebruikers'],[/organizations?/gi,'organisaties'],[/available/gi,'beschikbaar'],[/introducing/gi,'Introductie van'],[/announcement/gi,'aankondiging'],[/updates?/gi,'updates'],[/with microsoft 365 copilot/gi,'met Microsoft 365 Copilot'],[/for microsoft 365 copilot/gi,'voor Microsoft 365 Copilot']];
function dutchText(s:string){let out=clean(s);for(const [a,b] of dictionary)out=out.replace(a,b);out=out.replace(/\s+/g,' ').trim();return out}
function editorialTitle(title:string,p:string){let t=dutchText(title);if(!/[a-z]/.test(t))return title;const lower=t.toLowerCase();if(lower.startsWith('how to '))t='Zo gebruik je '+t.slice(7);else if(lower.startsWith('how '))t='Zo werkt '+t.slice(4);else if(lower.startsWith('use '))t='Gebruik '+t.slice(4);if(!/copilot|work iq/i.test(t)&&p)t=`${p}: ${t}`;return t.charAt(0).toUpperCase()+t.slice(1)}
function editorialDescription(raw:string,p:string,status:string){const s=dutchText(raw);const prefix=status==='Licentie-update'?'Microsoft publiceert een wijziging rond licenties, prijzen of facturatie. ':status==='Release notes'?'Microsoft heeft de release-informatie bijgewerkt. ':status==='Aankondiging'?'Microsoft kondigt een nieuwe Copilot-ontwikkeling aan. ':'Microsoft heeft nieuwe informatie over Copilot gepubliceerd. ';
 if(!s)return `${prefix}Bekijk wat dit betekent voor ${p}, beschikbaarheid en gebruik binnen Microsoft 365.`;
 const clipped=s.length>300?s.slice(0,297).replace(/\s+\S*$/,'')+'…':s;
 return `${prefix}${clipped}`}
function statusFor(s:string){if(/licen|billing|pricing|credit|subscription|csp/i.test(s))return'Licentie-update';if(/release note/i.test(s))return'Release notes';if(/introduc|announc|launch/i.test(s))return'Aankondiging';return'Microsoft update'}
const seed:Item[]=[
 {title:'4 manieren om te leren bouwen met Microsoft Copilot Studio',url:'https://www.microsoft.com/en-us/copilot/blog/copilot-studio/4-ways-to-learn-how-to-build-with-microsoft-copilot-studio/',description:'Microsoft bundelt vier praktische leerpaden voor Copilot Studio: verkennen, hands-on bouwen, vaardigheden valideren en gericht doorgroeien.',date:'2026-10-01T12:00:00Z',source:'Microsoft Copilot Blog',product:'Copilot Studio',status:'Microsoft update'},
 {title:'Usage-based billing voor nieuwe Microsoft 365 Copilot Business-licenties',url:'https://learn.microsoft.com/en-us/partner-center/announcements/2026-october',description:'Microsoft wijzigt usage-based billing voor nieuwe Microsoft 365 Copilot Business-abonnementen via CSP, inclusief Copilot Credits, bestedingslimieten en beschikbaarheid.',date:'2026-10-01T12:00:00Z',source:'Microsoft Learn / Partner Center',product:'Microsoft 365 Copilot',status:'Licentie-update'},
 {title:'Wat is nieuw in Microsoft Copilot – september 2026',url:'https://techcommunity.microsoft.com/blog/microsoft-copilot-blog/what%E2%80%99s-new-in-microsoft-copilot--september-2026/4559107',description:'Microsoft bundelt nieuwe Copilot-mogelijkheden voor Teams, Outlook, Word, PowerPoint, SharePoint, OneDrive, agents, connectors en beheer.',date:'2026-09-30T12:00:00Z',source:'Microsoft Community Hub',product:'Microsoft 365 Copilot',status:'Microsoft update'}
];
async function learn(q:string){try{const u=`https://learn.microsoft.com/api/search?search=${encodeURIComponent(q)}&locale=en-us&$top=35`;const r=await fetch(u,{headers:{Accept:'application/json','User-Agent':'Daily-Microsoft-Copilot/6.0'},cache:'no-store'});if(!r.ok)return[];const j=await r.json();return (Array.isArray(j.results)?j.results:[]).map((x:LearnResult)=>{let url=x.url||'';if(!url.startsWith('http'))url='https://learn.microsoft.com'+(url.startsWith('/')?'':'/')+url;let date:string|null=null;if(x.lastUpdatedDate){const d=new Date(x.lastUpdatedDate);if(!Number.isNaN(d.getTime()))date=d.toISOString()}const rawTitle=clean(x.title),rawDescription=clean(x.description),p=product(`${rawTitle} ${rawDescription}`),status=statusFor(`${rawTitle} ${rawDescription}`);return{title:editorialTitle(rawTitle,p),url,description:editorialDescription(rawDescription,p,status),date,source:'Microsoft Learn',product:p,status} as Item})}catch{return[]}}
export async function GET(){try{const groups=await Promise.all(queries.map(learn));const now=new Date(),oldest=new Date(now);oldest.setUTCDate(oldest.getUTCDate()-14);oldest.setUTCHours(0,0,0,0);const seen=new Set<string>();const fresh=[...seed,...groups.flat()].filter(x=>{if(!x.title||!x.url||!x.date||!relevant(`${x.title} ${x.description}`))return false;let host='';try{host=new URL(x.url).hostname.toLowerCase()}catch{return false}if(!trustedHosts.has(host))return false;const d=new Date(x.date);if(Number.isNaN(d.getTime())||d<oldest||d>now)return false;const key=x.url.split('?')[0].replace(/\/$/,'').toLowerCase();if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,300);let items=fresh,persisted=0;if(databaseEnabled()){persisted=await saveNews(fresh);items=await readArchive(1000)}return NextResponse.json({items,updatedAt:new Date().toISOString(),windowDays:14,persistentArchive:databaseEnabled(),persisted,count:items.length,language:'nl-NL',originalSourceLinks:true,sources:['Microsoft Learn','Microsoft 365 Copilot release notes','AI at Work Roadmap','Microsoft Copilot Blog','Microsoft Community Hub','Official Microsoft Blog','Microsoft Partner Center']},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);let items=seed;try{if(databaseEnabled()){const archived=await readArchive(1000);if(archived.length)items=archived}}catch{}return NextResponse.json({items,persistentArchive:databaseEnabled(),error:'Live nieuws kon niet volledig worden opgehaald'},{status:200,headers:{'Cache-Control':'no-store'}})}}
